#!/bin/bash
read -p "Username: " usr
read -p "E-Mail:   " email
read -p "Password: " pass
echo "https://$usr:$pass@github.com/$usr" > ~/.gitauto

git config --add user.name $usr
git config --add user.email $email
