#!/bin/bash
read -p "Username: " usr
read -p "E-Mail:   " email
echo "ssh://git@github.com/$usr" > ~/.gitauto
echo "Execute:
ssh-keygen -t ed25519 -C '$usr@github.com'
To generate an SSH key for your GitHub"
git config --global user.name "$usr"
git config --global user.email "$email"
