#!/bin/bash
path=".git/.gitauto"
echo "\n" >> ./$path
while IFS= read -r line
do
	if [[ "$line" == "branch:"* ]]
	then
		echo "GIT: Pulling..."
		git pull origin ${line:7}
		exit
	fi
done < ./$path
read -p "Branch: " branch
echo "branch:$branch" >> ./$path
echo "GIT: Pulling..."
git pull origin $branch
